// 扩展的模拟数据
export const mockRepositories = [
  {
    repository_id: "1",
    name: "GenBank",
    description:
      "GenBank is the NIH genetic sequence database, an annotated collection of all publicly available DNA sequences.",
    repository_url: "https://www.ncbi.nlm.nih.gov/genbank/",
    institutions: [{ name: "NCBI", country: "United States", coordinates: [38.9072, -77.0369] }],
    subjects: [{ text: "Genomics" }, { text: "Genetics" }, { text: "Molecular Biology" }],
    content_types: ["DNA sequence", "RNA sequence", "Genomic data"],
    certificates: ["CoreTrustSeal", "ISO 27001"],
    source: "re3data",
    last_update: new Date("2024-01-15"),
    size: "2.5TB",
    records_count: "250M+",
    api_status: "active",
    rating: 4.8,
    downloads_monthly: 125000,
    citations: 15420,
    established: 1982,
    access_type: "Open Access",
    data_formats: ["FASTA", "GenBank", "XML"],
    languages: ["English"],
    license: "Public Domain",
  },
  {
    repository_id: "2",
    name: "UniProt",
    description:
      "The Universal Protein Resource (UniProt) is a comprehensive resource for protein sequence and annotation data.",
    repository_url: "https://www.uniprot.org/",
    institutions: [
      { name: "EMBL-EBI", country: "United Kingdom", coordinates: [52.0799, 0.1873] },
      { name: "SIB", country: "Switzerland", coordinates: [46.5197, 6.6323] },
    ],
    subjects: [{ text: "Proteomics" }, { text: "Bioinformatics" }, { text: "Structural Biology" }],
    content_types: ["Protein sequence", "Protein structure", "Functional annotation"],
    certificates: ["FAIR", "CoreTrustSeal"],
    source: "fairsharing",
    last_update: new Date("2024-02-01"),
    size: "1.8TB",
    records_count: "220M+",
    api_status: "active",
    rating: 4.9,
    downloads_monthly: 98000,
    citations: 22100,
    established: 2002,
    access_type: "Open Access",
    data_formats: ["FASTA", "XML", "RDF"],
    languages: ["English"],
    license: "CC BY 4.0",
  },
  {
    repository_id: "3",
    name: "PDB",
    description:
      "The Protein Data Bank is the single worldwide archive of structural data of biological macromolecules.",
    repository_url: "https://www.rcsb.org/",
    institutions: [{ name: "RCSB", country: "United States", coordinates: [40.7128, -74.006] }],
    subjects: [{ text: "Structural Biology" }, { text: "Biochemistry" }, { text: "Crystallography" }],
    content_types: ["3D structure", "Protein structure", "Crystallographic data"],
    certificates: ["CoreTrustSeal", "ISO 27001", "FAIR"],
    source: "gcbr",
    last_update: new Date("2024-01-20"),
    size: "850GB",
    records_count: "200K+",
    api_status: "active",
    rating: 4.7,
    downloads_monthly: 75000,
    citations: 18900,
    established: 1971,
    access_type: "Open Access",
    data_formats: ["PDB", "mmCIF", "XML"],
    languages: ["English"],
    license: "CC0 1.0",
  },
  {
    repository_id: "4",
    name: "ArrayExpress",
    description: "ArrayExpress is a database of functional genomics experiments including gene expression data.",
    repository_url: "https://www.ebi.ac.uk/arrayexpress/",
    institutions: [{ name: "EMBL-EBI", country: "United Kingdom", coordinates: [52.0799, 0.1873] }],
    subjects: [{ text: "Genomics" }, { text: "Gene Expression" }, { text: "Transcriptomics" }],
    content_types: ["Gene expression data", "Microarray data", "RNA-seq data"],
    certificates: ["FAIR", "CoreTrustSeal"],
    source: "fairsharing",
    last_update: new Date("2024-01-10"),
    size: "3.2TB",
    records_count: "180K+",
    api_status: "maintenance",
    rating: 4.5,
    downloads_monthly: 45000,
    citations: 8750,
    established: 2003,
    access_type: "Open Access",
    data_formats: ["MAGE-TAB", "JSON", "XML"],
    languages: ["English"],
    license: "CC BY 4.0",
  },
  {
    repository_id: "5",
    name: "ChEMBL",
    description: "ChEMBL is a manually curated database of bioactive molecules with drug-like properties.",
    repository_url: "https://www.ebi.ac.uk/chembl/",
    institutions: [{ name: "EMBL-EBI", country: "United Kingdom", coordinates: [52.0799, 0.1873] }],
    subjects: [{ text: "Chemistry" }, { text: "Drug Discovery" }, { text: "Pharmacology" }],
    content_types: ["Chemical structures", "Bioactivity data", "Drug data"],
    certificates: ["FAIR"],
    source: "gcbr",
    last_update: new Date("2024-02-05"),
    size: "1.1TB",
    records_count: "2.3M+",
    api_status: "active",
    rating: 4.6,
    downloads_monthly: 32000,
    citations: 12400,
    established: 2009,
    access_type: "Open Access",
    data_formats: ["SDF", "JSON", "RDF"],
    languages: ["English"],
    license: "CC BY-SA 3.0",
  },
  {
    repository_id: "6",
    name: "NCBI SRA",
    description: "The Sequence Read Archive (SRA) stores raw sequencing data and alignment information.",
    repository_url: "https://www.ncbi.nlm.nih.gov/sra",
    institutions: [{ name: "NCBI", country: "United States", coordinates: [38.9072, -77.0369] }],
    subjects: [{ text: "Genomics" }, { text: "Sequencing" }, { text: "Next-generation sequencing" }],
    content_types: ["Raw sequencing data", "NGS data", "Alignment data"],
    certificates: ["CoreTrustSeal"],
    source: "re3data",
    last_update: new Date("2024-01-25"),
    size: "45TB",
    records_count: "15M+",
    api_status: "active",
    rating: 4.4,
    downloads_monthly: 89000,
    citations: 9800,
    established: 2007,
    access_type: "Open Access",
    data_formats: ["FASTQ", "SRA", "BAM"],
    languages: ["English"],
    license: "Public Domain",
  },
  {
    repository_id: "7",
    name: "EMBL-ENA",
    description: "The European Nucleotide Archive provides comprehensive record of nucleotide sequencing information.",
    repository_url: "https://www.ebi.ac.uk/ena/",
    institutions: [{ name: "EMBL-EBI", country: "United Kingdom", coordinates: [52.0799, 0.1873] }],
    subjects: [{ text: "Genomics" }, { text: "Nucleotide sequences" }, { text: "Phylogenetics" }],
    content_types: ["Nucleotide sequences", "Assembly data", "Annotation"],
    certificates: ["FAIR", "CoreTrustSeal"],
    source: "fairsharing",
    last_update: new Date("2024-02-10"),
    size: "38TB",
    records_count: "400M+",
    api_status: "active",
    rating: 4.7,
    downloads_monthly: 67000,
    citations: 11200,
    established: 1980,
    access_type: "Open Access",
    data_formats: ["EMBL", "FASTA", "XML"],
    languages: ["English"],
    license: "CC0 1.0",
  },
  {
    repository_id: "8",
    name: "PRIDE",
    description: "PRIDE is a centralized, standards compliant, public data repository for proteomics data.",
    repository_url: "https://www.ebi.ac.uk/pride/",
    institutions: [{ name: "EMBL-EBI", country: "United Kingdom", coordinates: [52.0799, 0.1873] }],
    subjects: [{ text: "Proteomics" }, { text: "Mass Spectrometry" }, { text: "Protein identification" }],
    content_types: ["Mass spectrometry data", "Protein identification", "Quantitative data"],
    certificates: ["FAIR"],
    source: "gcbr",
    last_update: new Date("2024-01-30"),
    size: "12TB",
    records_count: "25K+",
    api_status: "active",
    rating: 4.3,
    downloads_monthly: 18000,
    citations: 5600,
    established: 2005,
    access_type: "Open Access",
    data_formats: ["mzML", "PRIDE XML", "mzTab"],
    languages: ["English"],
    license: "CC BY 4.0",
  },
]

// 统计数据
export const mockStats = {
  totalRepositories: mockRepositories.length,
  totalRecords: "1.2B+",
  totalSize: "104TB",
  activeAPIs: mockRepositories.filter((r) => r.api_status === "active").length,
  averageRating: 4.6,
  totalDownloads: mockRepositories.reduce((sum, repo) => sum + repo.downloads_monthly, 0),
  totalCitations: mockRepositories.reduce((sum, repo) => sum + repo.citations, 0),
  subjectDistribution: [
    { name: "Genomics", count: 4, percentage: 50 },
    { name: "Proteomics", count: 2, percentage: 25 },
    { name: "Chemistry", count: 1, percentage: 12.5 },
    { name: "Structural Biology", count: 1, percentage: 12.5 },
  ],
  countryDistribution: [
    { name: "United Kingdom", count: 5, percentage: 62.5 },
    { name: "United States", count: 2, percentage: 25 },
    { name: "Switzerland", count: 1, percentage: 12.5 },
  ],
  monthlyTrends: [
    { month: "Jan", downloads: 420000, citations: 1200 },
    { month: "Feb", downloads: 445000, citations: 1350 },
    { month: "Mar", downloads: 468000, citations: 1280 },
    { month: "Apr", downloads: 492000, citations: 1420 },
    { month: "May", downloads: 515000, citations: 1380 },
    { month: "Jun", downloads: 538000, citations: 1450 },
  ],
}

// 新闻数据
export const mockNews = [
  {
    id: "1",
    title: "New FAIR Data Principles Implementation in Major Repositories",
    summary: "Leading scientific repositories announce enhanced FAIR data compliance measures.",
    date: new Date("2024-02-15"),
    source: "Nature Data",
    category: "Policy",
    url: "#",
  },
  {
    id: "2",
    title: "GenBank Reaches 250 Million Sequence Milestone",
    summary: "NCBI's GenBank database celebrates a major milestone with over 250 million sequences.",
    date: new Date("2024-02-10"),
    source: "Science News",
    category: "Milestone",
    url: "#",
  },
  {
    id: "3",
    title: "European Data Infrastructure Expansion Announced",
    summary: "EMBL-EBI announces significant infrastructure upgrades to support growing data volumes.",
    date: new Date("2024-02-05"),
    source: "Research Europe",
    category: "Infrastructure",
    url: "#",
  },
]
