import type { Theme } from "@/types/theme"

export const themes: Record<string, Theme> = {
    light: {
        name: "Light",
        colors: {
            background: "#ffffff",
            card: "#f8fafc",
            text: "#1e293b",
            textMuted: "#64748b",
            primary: "#3b82f6",
            secondary: "#dbe3e0",
            accent: "#8b5cf6",
            border: "#e2e8f0",
            hover: "#f1f5f9",
        },
    },
    dark: {
        name: "Dark",
        colors: {
            background: "#0f172a",
            card: "#1e293b",
            text: "#f1f5f9",
            textMuted: "#94a3b8",
            primary: "#60a5fa",
            secondary: "#34d399",
            accent: "#a78bfa",
            border: "#334155",
            hover: "#334155",
        },
    },
    blue: {
        name: "Ocean Blue",
        colors: {
            background: "#f0f9ff",
            card: "#e0f2fe",
            text: "#0c4a6e",
            textMuted: "#0369a1",
            primary: "#0ea5e9",
            secondary: "#06b6d4",
            accent: "#3b82f6",
            border: "#bae6fd",
            hover: "#e0f2fe",
        },
        gradients: {
            background: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)",
            card: "linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)",
        },
    },
    green: {
        name: "Forest Green",
        colors: {
            background: "#f0fdf4",
            card: "#dcfce7",
            text: "#14532d",
            textMuted: "#166534",
            primary: "#10b981",
            secondary: "#059669",
            accent: "#34d399",
            border: "#bbf7d0",
            hover: "#dcfce7",
        },
        gradients: {
            background: "linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)",
            card: "linear-gradient(135deg, #dcfce7 0%, #bbf7d0 100%)",
        },
    },
    purple: {
        name: "Royal Purple",
        colors: {
            background: "#faf5ff",
            card: "#f3e8ff",
            text: "#581c87",
            textMuted: "#7c3aed",
            primary: "#8b5cf6",
            secondary: "#a78bfa",
            accent: "#c084fc",
            border: "#e9d5ff",
            hover: "#f3e8ff",
        },
        gradients: {
            background: "linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)",
            card: "linear-gradient(135deg, #f3e8ff 0%, #e9d5ff 100%)",
        },
    },
    warm: {
        name: "Warm Sunset",
        colors: {
            background: "#fffbeb",
            card: "#fef3c7",
            text: "#92400e",
            textMuted: "#d97706",
            primary: "#f59e0b",
            secondary: "#f97316",
            accent: "#fbbf24",
            border: "#fed7aa",
            hover: "#fef3c7",
        },
        gradients: {
            background: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)",
            card: "linear-gradient(135deg, #fef3c7 0%, #fed7aa 100%)",
        },
        animations: {
            duration: "0.3s",
            easing: "ease-in-out",
        },
    },
    autumn: {
        name: "Autumn",
        colors: {
            background: "#fef2f2",
            card: "#fee2e2",
            text: "#7f1d1d",
            textMuted: "#dc2626",
            primary: "#ef4444",
            secondary: "#f97316",
            accent: "#fbbf24",
            border: "#fecaca",
            hover: "#fee2e2",
        },
        gradients: {
            background: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)",
            card: "linear-gradient(135deg, #fee2e2 0%, #fecaca 100%)",
        },
    },
    winter: {
        name: "Winter",
        colors: {
            background: "#f0fdfa",
            card: "#ccfbf1",
            text: "#134e4a",
            textMuted: "#0f766e",
            primary: "#06b6d4",
            secondary: "#0891b2",
            accent: "#22d3ee",
            border: "#a7f3d0",
            hover: "#ccfbf1",
        },
        gradients: {
            background: "linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%)",
            card: "linear-gradient(135deg, #ccfbf1 0%, #a7f3d0 100%)",
        },
    },
    spring: {
        name: "Spring",
        colors: {
            background: "#f7fee7",
            card: "#ecfccb",
            text: "#365314",
            textMuted: "#4d7c0f",
            primary: "#84cc16",
            secondary: "#65a30d",
            accent: "#a3e635",
            border: "#d9f99d",
            hover: "#ecfccb",
        },
        gradients: {
            background: "linear-gradient(135deg, #f7fee7 0%, #ecfccb 100%)",
            card: "linear-gradient(135deg, #ecfccb 0%, #d9f99d 100%)",
        },
    },
    summer: {
        name: "Summer",
        colors: {
            background: "#fff7ed",
            card: "#fed7aa",
            text: "#9a3412",
            textMuted: "#ea580c",
            primary: "#f97316",
            secondary: "#fb923c",
            accent: "#fdba74",
            border: "#fed7aa",
            hover: "#fed7aa",
        },
        gradients: {
            background: "linear-gradient(135deg, #fff7ed 0%, #fed7aa 100%)",
            card: "linear-gradient(135deg, #fed7aa 0%, #fdba74 100%)",
        },
    },
}
